FORMAT: 1A
HOST: http://app.climb.social/api/

# Climb API

A super-simple public service for getting content out of Climb.

## Collections [/collections/{collection_id}]

Collections are the individual feeds you make within Climb.

### List all approved items [GET]

Returns a list of items which have been moderated and approved in the Climb admin.

+ Parameters
    + collection_id (number) - ID of the Climb collection you want to pull in.


+ Response 200 (application/json)

    [
        {
            "question": "Favourite programming language?",
            "published_at": "2014-11-11T08:40:51.620Z",
            "url": "/questions/1",
            "choices": [
                {
                    "choice": "Swift",
                    "url": "/questions/1/choices/1",
                    "votes": 2048
                }, {
                    "choice": "Python",
                    "url": "/questions/1/choices/2",
                    "votes": 1024
                }, {
                    "choice": "Objective-C",
                    "url": "/questions/1/choices/3",
                    "votes": 512
                }, {
                    "choice": "Ruby",
                    "url": "/questions/1/choices/4",
                    "votes": 256
                }
            ]
        }
    ]

