FORMAT: 1A
HOST: http://app.climb.social/api/

# Climb API

A super-simple public service for getting content out of Climb.

# Group Collections

Collections are the individual feeds you make within Climb. The represent different hashtags, users and social networks all in one place.

## Collection [/collections/{collection_id}{?since}{?max}{?callback}]

+ Parameters
    + collection_id (string, required) - ID of the Climb collection you want to pull in.

    + since (long, optional) - Timestamp you'd like to collect published items from.

        Sometimes you only want gather the approved items from a certain moment in time.    

    + max (long, optional) - The timestamp you'd like to collect published items until.
    
        Sometimes you may want to collect all approve items up to a point in time.

    + callback (JavaScript function, optional) - Function to call if you want to make a `JSONP` request.


### Approved items in collection [GET]

Returns a list of items which have been moderated and approved within the Climb admin.


+ Response 200 (application/json)

            [
                {
                    collection_id: string,
                    source_type: string  (enum:{instagram,twitter,facebook,anything}),
                    video_url: string,
                    timestamp: long,
                    image: {
                        url: string,
                        width: int,
                        height: int,
                    },
                    message: string,
                    author: {
                        picture: string,
                        name: string,
                        username: string,
                        link: string,
                        followers_count: int
                    }
                },
                
                ...
            ]

